server:
  port: 8010
user:
  userServiceUrl: http://localhost:8000/

spring:
  application:
    name: onsumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true